import type { EvaluationResult, EvaluationRun, NormalizedSpan } from "../src/index.js";

export const projectId = "10000000-0000-4000-8000-000000000001";

export function normalizedSpan(overrides: Partial<NormalizedSpan> = {}): NormalizedSpan {
  return {
    projectId,
    traceId: "a".repeat(32),
    spanId: "b".repeat(16),
    parentSpanId: null,
    traceState: "",
    name: "test span",
    kind: 1,
    observationKind: "span",
    status: "ok",
    statusMessage: "",
    startTimeUnixNano: "1",
    endTimeUnixNano: "2",
    durationNano: "1",
    serviceName: "test",
    scopeName: "test",
    scopeVersion: "1",
    resourceAttributes: {},
    spanAttributes: {},
    events: [],
    links: [],
    traceName: null,
    userId: null,
    sessionId: null,
    tags: [],
    version: null,
    environment: "test",
    release: null,
    serviceVersion: null,
    model: null,
    inputTokens: 0,
    cachedInputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    inputCost: null,
    outputCost: null,
    totalCost: null,
    input: null,
    output: null,
    expiresAt: null,
    ingestedAt: "2026-09-17T00:00:00.000Z",
    ingestVersion: "1",
    ...overrides,
  };
}

export function evaluationResult(overrides: Partial<EvaluationResult> = {}): EvaluationResult {
  return {
    projectId,
    id: "evaluation-1",
    runId: null,
    timestamp: "2026-09-17T00:00:00.000Z",
    traceId: null,
    observationId: null,
    responseId: null,
    suiteName: "test",
    caseId: null,
    metricName: "quality",
    outcome: "pass",
    dataType: null,
    numericValue: null,
    categoricalValue: null,
    explanation: null,
    payload: null,
    payloadStatus: "not_requested",
    configId: null,
    serviceName: "test",
    environment: "test",
    release: null,
    metadata: {},
    source: "telemetry",
    reviewer: null,
    expiresAt: null,
    ingestedAt: "2026-09-17T00:00:00.000Z",
    ingestVersion: "1",
    ...overrides,
  };
}

export function evaluationRun(overrides: Partial<EvaluationRun> = {}): EvaluationRun {
  return {
    projectId,
    id: "run-1",
    status: "completed",
    suiteName: "test",
    startedAt: "2026-09-17T00:00:00.000Z",
    completedAt: "2026-09-17T00:01:00.000Z",
    durationMs: 60_000,
    caseCount: 1,
    metricNames: ["quality"],
    passed: 1,
    failed: 0,
    invalid: 0,
    serviceName: "test",
    environment: "test",
    release: null,
    datasetName: null,
    datasetVersion: null,
    promptName: null,
    promptVersion: null,
    metadata: {},
    expiresAt: null,
    ingestedAt: "2026-09-17T00:00:00.000Z",
    ingestVersion: "1",
    stateVersion: 2,
    ...overrides,
  };
}
