/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteRouteImport } from './routes/$projectId/route'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdOnboardingRouteImport } from './routes/$projectId/onboarding'
import { Route as ProjectIdSettingsRouteImport } from './routes/$projectId/settings'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as ProjectIdSessionsIndexRouteImport } from './routes/$projectId/sessions/index'
import { Route as ProjectIdSessionsSessionIdRouteImport } from './routes/$projectId/sessions/$sessionId'
import { Route as ProjectIdTracesIndexRouteImport } from './routes/$projectId/traces/index'
import { Route as ProjectIdTracesTraceIdRouteImport } from './routes/$projectId/traces/$traceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRouteRoute = ProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdOnboardingRoute = ProjectIdOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdSettingsRoute = ProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSessionsIndexRoute = ProjectIdSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdSessionsSessionIdRoute =
  ProjectIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdTracesIndexRoute = ProjectIdTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdTracesTraceIdRoute = ProjectIdTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteRouteWithChildren
  '/members': typeof MembersRoute
  '/$projectId/onboarding': typeof ProjectIdOnboardingRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/sessions/': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces/': typeof ProjectIdTracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members': typeof MembersRoute
  '/$projectId/onboarding': typeof ProjectIdOnboardingRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/sessions': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces': typeof ProjectIdTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteRouteWithChildren
  '/members': typeof MembersRoute
  '/$projectId/onboarding': typeof ProjectIdOnboardingRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/sessions/': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces/': typeof ProjectIdTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/members'
    | '/$projectId/onboarding'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId/'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/sessions/'
    | '/$projectId/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/members'
    | '/$projectId/onboarding'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/sessions'
    | '/$projectId/traces'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/members'
    | '/$projectId/onboarding'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId/'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/sessions/'
    | '/$projectId/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRouteRoute: typeof ProjectIdRouteRouteWithChildren
  MembersRoute: typeof MembersRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/onboarding': {
      id: '/$projectId/onboarding'
      path: '/onboarding'
      fullPath: '/$projectId/onboarding'
      preLoaderRoute: typeof ProjectIdOnboardingRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/settings': {
      id: '/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof ProjectIdSettingsRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/sessions/': {
      id: '/$projectId/sessions/'
      path: '/sessions'
      fullPath: '/$projectId/sessions/'
      preLoaderRoute: typeof ProjectIdSessionsIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/sessions/$sessionId': {
      id: '/$projectId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/': {
      id: '/$projectId/traces/'
      path: '/traces'
      fullPath: '/$projectId/traces/'
      preLoaderRoute: typeof ProjectIdTracesIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/$traceId': {
      id: '/$projectId/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/$projectId/traces/$traceId'
      preLoaderRoute: typeof ProjectIdTracesTraceIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
  }
}

interface ProjectIdRouteRouteChildren {
  ProjectIdOnboardingRoute: typeof ProjectIdOnboardingRoute
  ProjectIdSettingsRoute: typeof ProjectIdSettingsRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdSessionsSessionIdRoute: typeof ProjectIdSessionsSessionIdRoute
  ProjectIdTracesTraceIdRoute: typeof ProjectIdTracesTraceIdRoute
  ProjectIdSessionsIndexRoute: typeof ProjectIdSessionsIndexRoute
  ProjectIdTracesIndexRoute: typeof ProjectIdTracesIndexRoute
}

const ProjectIdRouteRouteChildren: ProjectIdRouteRouteChildren = {
  ProjectIdOnboardingRoute: ProjectIdOnboardingRoute,
  ProjectIdSettingsRoute: ProjectIdSettingsRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdSessionsSessionIdRoute: ProjectIdSessionsSessionIdRoute,
  ProjectIdTracesTraceIdRoute: ProjectIdTracesTraceIdRoute,
  ProjectIdSessionsIndexRoute: ProjectIdSessionsIndexRoute,
  ProjectIdTracesIndexRoute: ProjectIdTracesIndexRoute,
}

const ProjectIdRouteRouteWithChildren = ProjectIdRouteRoute._addFileChildren(
  ProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRouteRoute: ProjectIdRouteRouteWithChildren,
  MembersRoute: MembersRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
