/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteRouteImport } from './routes/$projectId/route'
import { Route as LlmModelsRouteImport } from './routes/llm-models'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdConnectRouteImport } from './routes/$projectId/connect'
import { Route as ProjectIdEvaluationsRouteImport } from './routes/$projectId/evaluations'
import { Route as ProjectIdSettingsRouteImport } from './routes/$projectId/settings'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as ProjectIdSessionsIndexRouteImport } from './routes/$projectId/sessions/index'
import { Route as ProjectIdSessionsSessionIdRouteImport } from './routes/$projectId/sessions/$sessionId'
import { Route as ProjectIdTracesIndexRouteImport } from './routes/$projectId/traces/index'
import { Route as ProjectIdTracesTraceIdRouteImport } from './routes/$projectId/traces/$traceId'
import { Route as ProjectIdTracesCompareRouteImport } from './routes/$projectId/traces/compare'
import { Route as ProjectIdUsersIndexRouteImport } from './routes/$projectId/users/index'
import { Route as ProjectIdUsersUserIdRouteImport } from './routes/$projectId/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRouteRoute = ProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmModelsRoute = LlmModelsRouteImport.update({
  id: '/llm-models',
  path: '/llm-models',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdConnectRoute = ProjectIdConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdEvaluationsRoute = ProjectIdEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdSettingsRoute = ProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSessionsIndexRoute = ProjectIdSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdSessionsSessionIdRoute =
  ProjectIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdTracesIndexRoute = ProjectIdTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdTracesTraceIdRoute = ProjectIdTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdTracesCompareRoute = ProjectIdTracesCompareRouteImport.update({
  id: '/traces/compare',
  path: '/traces/compare',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdUsersIndexRoute = ProjectIdUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdUsersUserIdRoute = ProjectIdUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteRouteWithChildren
  '/llm-models': typeof LlmModelsRoute
  '/members': typeof MembersRoute
  '/$projectId/connect': typeof ProjectIdConnectRoute
  '/$projectId/evaluations': typeof ProjectIdEvaluationsRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/traces/compare': typeof ProjectIdTracesCompareRoute
  '/$projectId/users/$userId': typeof ProjectIdUsersUserIdRoute
  '/$projectId/sessions/': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces/': typeof ProjectIdTracesIndexRoute
  '/$projectId/users/': typeof ProjectIdUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llm-models': typeof LlmModelsRoute
  '/members': typeof MembersRoute
  '/$projectId/connect': typeof ProjectIdConnectRoute
  '/$projectId/evaluations': typeof ProjectIdEvaluationsRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/traces/compare': typeof ProjectIdTracesCompareRoute
  '/$projectId/users/$userId': typeof ProjectIdUsersUserIdRoute
  '/$projectId/sessions': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces': typeof ProjectIdTracesIndexRoute
  '/$projectId/users': typeof ProjectIdUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteRouteWithChildren
  '/llm-models': typeof LlmModelsRoute
  '/members': typeof MembersRoute
  '/$projectId/connect': typeof ProjectIdConnectRoute
  '/$projectId/evaluations': typeof ProjectIdEvaluationsRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/traces/compare': typeof ProjectIdTracesCompareRoute
  '/$projectId/users/$userId': typeof ProjectIdUsersUserIdRoute
  '/$projectId/sessions/': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces/': typeof ProjectIdTracesIndexRoute
  '/$projectId/users/': typeof ProjectIdUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/llm-models'
    | '/members'
    | '/$projectId/connect'
    | '/$projectId/evaluations'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId/'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/traces/compare'
    | '/$projectId/users/$userId'
    | '/$projectId/sessions/'
    | '/$projectId/traces/'
    | '/$projectId/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llm-models'
    | '/members'
    | '/$projectId/connect'
    | '/$projectId/evaluations'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/traces/compare'
    | '/$projectId/users/$userId'
    | '/$projectId/sessions'
    | '/$projectId/traces'
    | '/$projectId/users'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/llm-models'
    | '/members'
    | '/$projectId/connect'
    | '/$projectId/evaluations'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId/'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/traces/compare'
    | '/$projectId/users/$userId'
    | '/$projectId/sessions/'
    | '/$projectId/traces/'
    | '/$projectId/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRouteRoute: typeof ProjectIdRouteRouteWithChildren
  LlmModelsRoute: typeof LlmModelsRoute
  MembersRoute: typeof MembersRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-models': {
      id: '/llm-models'
      path: '/llm-models'
      fullPath: '/llm-models'
      preLoaderRoute: typeof LlmModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/connect': {
      id: '/$projectId/connect'
      path: '/connect'
      fullPath: '/$projectId/connect'
      preLoaderRoute: typeof ProjectIdConnectRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/evaluations': {
      id: '/$projectId/evaluations'
      path: '/evaluations'
      fullPath: '/$projectId/evaluations'
      preLoaderRoute: typeof ProjectIdEvaluationsRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/settings': {
      id: '/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof ProjectIdSettingsRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/sessions/': {
      id: '/$projectId/sessions/'
      path: '/sessions'
      fullPath: '/$projectId/sessions/'
      preLoaderRoute: typeof ProjectIdSessionsIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/sessions/$sessionId': {
      id: '/$projectId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/': {
      id: '/$projectId/traces/'
      path: '/traces'
      fullPath: '/$projectId/traces/'
      preLoaderRoute: typeof ProjectIdTracesIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/$traceId': {
      id: '/$projectId/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/$projectId/traces/$traceId'
      preLoaderRoute: typeof ProjectIdTracesTraceIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/compare': {
      id: '/$projectId/traces/compare'
      path: '/traces/compare'
      fullPath: '/$projectId/traces/compare'
      preLoaderRoute: typeof ProjectIdTracesCompareRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/users/': {
      id: '/$projectId/users/'
      path: '/users'
      fullPath: '/$projectId/users/'
      preLoaderRoute: typeof ProjectIdUsersIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/users/$userId': {
      id: '/$projectId/users/$userId'
      path: '/users/$userId'
      fullPath: '/$projectId/users/$userId'
      preLoaderRoute: typeof ProjectIdUsersUserIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
  }
}

interface ProjectIdRouteRouteChildren {
  ProjectIdConnectRoute: typeof ProjectIdConnectRoute
  ProjectIdEvaluationsRoute: typeof ProjectIdEvaluationsRoute
  ProjectIdSettingsRoute: typeof ProjectIdSettingsRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdSessionsSessionIdRoute: typeof ProjectIdSessionsSessionIdRoute
  ProjectIdTracesTraceIdRoute: typeof ProjectIdTracesTraceIdRoute
  ProjectIdTracesCompareRoute: typeof ProjectIdTracesCompareRoute
  ProjectIdUsersUserIdRoute: typeof ProjectIdUsersUserIdRoute
  ProjectIdSessionsIndexRoute: typeof ProjectIdSessionsIndexRoute
  ProjectIdTracesIndexRoute: typeof ProjectIdTracesIndexRoute
  ProjectIdUsersIndexRoute: typeof ProjectIdUsersIndexRoute
}

const ProjectIdRouteRouteChildren: ProjectIdRouteRouteChildren = {
  ProjectIdConnectRoute: ProjectIdConnectRoute,
  ProjectIdEvaluationsRoute: ProjectIdEvaluationsRoute,
  ProjectIdSettingsRoute: ProjectIdSettingsRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdSessionsSessionIdRoute: ProjectIdSessionsSessionIdRoute,
  ProjectIdTracesTraceIdRoute: ProjectIdTracesTraceIdRoute,
  ProjectIdTracesCompareRoute: ProjectIdTracesCompareRoute,
  ProjectIdUsersUserIdRoute: ProjectIdUsersUserIdRoute,
  ProjectIdSessionsIndexRoute: ProjectIdSessionsIndexRoute,
  ProjectIdTracesIndexRoute: ProjectIdTracesIndexRoute,
  ProjectIdUsersIndexRoute: ProjectIdUsersIndexRoute,
}

const ProjectIdRouteRouteWithChildren = ProjectIdRouteRoute._addFileChildren(
  ProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRouteRoute: ProjectIdRouteRouteWithChildren,
  LlmModelsRoute: LlmModelsRoute,
  MembersRoute: MembersRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
