/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteRouteImport } from './routes/$projectId/route'
import { Route as LlmModelsRouteImport } from './routes/llm-models'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdConnectRouteImport } from './routes/$projectId/connect'
import { Route as ProjectIdSettingsRouteImport } from './routes/$projectId/settings'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as ProjectIdEvaluationsIndexRouteImport } from './routes/$projectId/evaluations/index'
import { Route as ProjectIdEvaluationsCompareRouteImport } from './routes/$projectId/evaluations/compare'
import { Route as ProjectIdEvaluationsGatesRouteImport } from './routes/$projectId/evaluations/gates'
import { Route as ProjectIdEvaluationsResultsRouteImport } from './routes/$projectId/evaluations/results'
import { Route as ProjectIdSessionsIndexRouteImport } from './routes/$projectId/sessions/index'
import { Route as ProjectIdSessionsSessionIdRouteImport } from './routes/$projectId/sessions/$sessionId'
import { Route as ProjectIdTracesIndexRouteImport } from './routes/$projectId/traces/index'
import { Route as ProjectIdTracesTraceIdRouteImport } from './routes/$projectId/traces/$traceId'
import { Route as ProjectIdTracesCompareRouteImport } from './routes/$projectId/traces/compare'
import { Route as ProjectIdUsersIndexRouteImport } from './routes/$projectId/users/index'
import { Route as ProjectIdUsersUserIdRouteImport } from './routes/$projectId/users/$userId'
import { Route as ProjectIdEvaluationsRunsIndexRouteImport } from './routes/$projectId/evaluations/runs/index'
import { Route as ProjectIdEvaluationsRunsRunIdRouteImport } from './routes/$projectId/evaluations/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRouteRoute = ProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmModelsRoute = LlmModelsRouteImport.update({
  id: '/llm-models',
  path: '/llm-models',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdConnectRoute = ProjectIdConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdSettingsRoute = ProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdEvaluationsIndexRoute =
  ProjectIdEvaluationsIndexRouteImport.update({
    id: '/evaluations/',
    path: '/evaluations/',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdEvaluationsCompareRoute =
  ProjectIdEvaluationsCompareRouteImport.update({
    id: '/evaluations/compare',
    path: '/evaluations/compare',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdEvaluationsGatesRoute =
  ProjectIdEvaluationsGatesRouteImport.update({
    id: '/evaluations/gates',
    path: '/evaluations/gates',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdEvaluationsResultsRoute =
  ProjectIdEvaluationsResultsRouteImport.update({
    id: '/evaluations/results',
    path: '/evaluations/results',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdSessionsIndexRoute = ProjectIdSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdSessionsSessionIdRoute =
  ProjectIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdTracesIndexRoute = ProjectIdTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdTracesTraceIdRoute = ProjectIdTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdTracesCompareRoute = ProjectIdTracesCompareRouteImport.update({
  id: '/traces/compare',
  path: '/traces/compare',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdUsersIndexRoute = ProjectIdUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdUsersUserIdRoute = ProjectIdUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdEvaluationsRunsIndexRoute =
  ProjectIdEvaluationsRunsIndexRouteImport.update({
    id: '/evaluations/runs/',
    path: '/evaluations/runs/',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)
const ProjectIdEvaluationsRunsRunIdRoute =
  ProjectIdEvaluationsRunsRunIdRouteImport.update({
    id: '/evaluations/runs/$runId',
    path: '/evaluations/runs/$runId',
    getParentRoute: () => ProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteRouteWithChildren
  '/llm-models': typeof LlmModelsRoute
  '/members': typeof MembersRoute
  '/$projectId/connect': typeof ProjectIdConnectRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/evaluations/compare': typeof ProjectIdEvaluationsCompareRoute
  '/$projectId/evaluations/gates': typeof ProjectIdEvaluationsGatesRoute
  '/$projectId/evaluations/results': typeof ProjectIdEvaluationsResultsRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/traces/compare': typeof ProjectIdTracesCompareRoute
  '/$projectId/users/$userId': typeof ProjectIdUsersUserIdRoute
  '/$projectId/evaluations/': typeof ProjectIdEvaluationsIndexRoute
  '/$projectId/sessions/': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces/': typeof ProjectIdTracesIndexRoute
  '/$projectId/users/': typeof ProjectIdUsersIndexRoute
  '/$projectId/evaluations/runs/$runId': typeof ProjectIdEvaluationsRunsRunIdRoute
  '/$projectId/evaluations/runs/': typeof ProjectIdEvaluationsRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llm-models': typeof LlmModelsRoute
  '/members': typeof MembersRoute
  '/$projectId/connect': typeof ProjectIdConnectRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/evaluations/compare': typeof ProjectIdEvaluationsCompareRoute
  '/$projectId/evaluations/gates': typeof ProjectIdEvaluationsGatesRoute
  '/$projectId/evaluations/results': typeof ProjectIdEvaluationsResultsRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/traces/compare': typeof ProjectIdTracesCompareRoute
  '/$projectId/users/$userId': typeof ProjectIdUsersUserIdRoute
  '/$projectId/evaluations': typeof ProjectIdEvaluationsIndexRoute
  '/$projectId/sessions': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces': typeof ProjectIdTracesIndexRoute
  '/$projectId/users': typeof ProjectIdUsersIndexRoute
  '/$projectId/evaluations/runs/$runId': typeof ProjectIdEvaluationsRunsRunIdRoute
  '/$projectId/evaluations/runs': typeof ProjectIdEvaluationsRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteRouteWithChildren
  '/llm-models': typeof LlmModelsRoute
  '/members': typeof MembersRoute
  '/$projectId/connect': typeof ProjectIdConnectRoute
  '/$projectId/settings': typeof ProjectIdSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/evaluations/compare': typeof ProjectIdEvaluationsCompareRoute
  '/$projectId/evaluations/gates': typeof ProjectIdEvaluationsGatesRoute
  '/$projectId/evaluations/results': typeof ProjectIdEvaluationsResultsRoute
  '/$projectId/sessions/$sessionId': typeof ProjectIdSessionsSessionIdRoute
  '/$projectId/traces/$traceId': typeof ProjectIdTracesTraceIdRoute
  '/$projectId/traces/compare': typeof ProjectIdTracesCompareRoute
  '/$projectId/users/$userId': typeof ProjectIdUsersUserIdRoute
  '/$projectId/evaluations/': typeof ProjectIdEvaluationsIndexRoute
  '/$projectId/sessions/': typeof ProjectIdSessionsIndexRoute
  '/$projectId/traces/': typeof ProjectIdTracesIndexRoute
  '/$projectId/users/': typeof ProjectIdUsersIndexRoute
  '/$projectId/evaluations/runs/$runId': typeof ProjectIdEvaluationsRunsRunIdRoute
  '/$projectId/evaluations/runs/': typeof ProjectIdEvaluationsRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/llm-models'
    | '/members'
    | '/$projectId/connect'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId/'
    | '/$projectId/evaluations/compare'
    | '/$projectId/evaluations/gates'
    | '/$projectId/evaluations/results'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/traces/compare'
    | '/$projectId/users/$userId'
    | '/$projectId/evaluations/'
    | '/$projectId/sessions/'
    | '/$projectId/traces/'
    | '/$projectId/users/'
    | '/$projectId/evaluations/runs/$runId'
    | '/$projectId/evaluations/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llm-models'
    | '/members'
    | '/$projectId/connect'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId'
    | '/$projectId/evaluations/compare'
    | '/$projectId/evaluations/gates'
    | '/$projectId/evaluations/results'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/traces/compare'
    | '/$projectId/users/$userId'
    | '/$projectId/evaluations'
    | '/$projectId/sessions'
    | '/$projectId/traces'
    | '/$projectId/users'
    | '/$projectId/evaluations/runs/$runId'
    | '/$projectId/evaluations/runs'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/llm-models'
    | '/members'
    | '/$projectId/connect'
    | '/$projectId/settings'
    | '/accept-invitation/$invitationId'
    | '/$projectId/'
    | '/$projectId/evaluations/compare'
    | '/$projectId/evaluations/gates'
    | '/$projectId/evaluations/results'
    | '/$projectId/sessions/$sessionId'
    | '/$projectId/traces/$traceId'
    | '/$projectId/traces/compare'
    | '/$projectId/users/$userId'
    | '/$projectId/evaluations/'
    | '/$projectId/sessions/'
    | '/$projectId/traces/'
    | '/$projectId/users/'
    | '/$projectId/evaluations/runs/$runId'
    | '/$projectId/evaluations/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRouteRoute: typeof ProjectIdRouteRouteWithChildren
  LlmModelsRoute: typeof LlmModelsRoute
  MembersRoute: typeof MembersRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-models': {
      id: '/llm-models'
      path: '/llm-models'
      fullPath: '/llm-models'
      preLoaderRoute: typeof LlmModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/connect': {
      id: '/$projectId/connect'
      path: '/connect'
      fullPath: '/$projectId/connect'
      preLoaderRoute: typeof ProjectIdConnectRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/settings': {
      id: '/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof ProjectIdSettingsRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/evaluations/': {
      id: '/$projectId/evaluations/'
      path: '/evaluations'
      fullPath: '/$projectId/evaluations/'
      preLoaderRoute: typeof ProjectIdEvaluationsIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/evaluations/compare': {
      id: '/$projectId/evaluations/compare'
      path: '/evaluations/compare'
      fullPath: '/$projectId/evaluations/compare'
      preLoaderRoute: typeof ProjectIdEvaluationsCompareRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/evaluations/gates': {
      id: '/$projectId/evaluations/gates'
      path: '/evaluations/gates'
      fullPath: '/$projectId/evaluations/gates'
      preLoaderRoute: typeof ProjectIdEvaluationsGatesRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/evaluations/results': {
      id: '/$projectId/evaluations/results'
      path: '/evaluations/results'
      fullPath: '/$projectId/evaluations/results'
      preLoaderRoute: typeof ProjectIdEvaluationsResultsRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/sessions/': {
      id: '/$projectId/sessions/'
      path: '/sessions'
      fullPath: '/$projectId/sessions/'
      preLoaderRoute: typeof ProjectIdSessionsIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/sessions/$sessionId': {
      id: '/$projectId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/': {
      id: '/$projectId/traces/'
      path: '/traces'
      fullPath: '/$projectId/traces/'
      preLoaderRoute: typeof ProjectIdTracesIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/$traceId': {
      id: '/$projectId/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/$projectId/traces/$traceId'
      preLoaderRoute: typeof ProjectIdTracesTraceIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/traces/compare': {
      id: '/$projectId/traces/compare'
      path: '/traces/compare'
      fullPath: '/$projectId/traces/compare'
      preLoaderRoute: typeof ProjectIdTracesCompareRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/users/': {
      id: '/$projectId/users/'
      path: '/users'
      fullPath: '/$projectId/users/'
      preLoaderRoute: typeof ProjectIdUsersIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/users/$userId': {
      id: '/$projectId/users/$userId'
      path: '/users/$userId'
      fullPath: '/$projectId/users/$userId'
      preLoaderRoute: typeof ProjectIdUsersUserIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/evaluations/runs/': {
      id: '/$projectId/evaluations/runs/'
      path: '/evaluations/runs'
      fullPath: '/$projectId/evaluations/runs/'
      preLoaderRoute: typeof ProjectIdEvaluationsRunsIndexRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    '/$projectId/evaluations/runs/$runId': {
      id: '/$projectId/evaluations/runs/$runId'
      path: '/evaluations/runs/$runId'
      fullPath: '/$projectId/evaluations/runs/$runId'
      preLoaderRoute: typeof ProjectIdEvaluationsRunsRunIdRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
  }
}

interface ProjectIdRouteRouteChildren {
  ProjectIdConnectRoute: typeof ProjectIdConnectRoute
  ProjectIdSettingsRoute: typeof ProjectIdSettingsRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdEvaluationsCompareRoute: typeof ProjectIdEvaluationsCompareRoute
  ProjectIdEvaluationsGatesRoute: typeof ProjectIdEvaluationsGatesRoute
  ProjectIdEvaluationsResultsRoute: typeof ProjectIdEvaluationsResultsRoute
  ProjectIdSessionsSessionIdRoute: typeof ProjectIdSessionsSessionIdRoute
  ProjectIdTracesTraceIdRoute: typeof ProjectIdTracesTraceIdRoute
  ProjectIdTracesCompareRoute: typeof ProjectIdTracesCompareRoute
  ProjectIdUsersUserIdRoute: typeof ProjectIdUsersUserIdRoute
  ProjectIdEvaluationsIndexRoute: typeof ProjectIdEvaluationsIndexRoute
  ProjectIdSessionsIndexRoute: typeof ProjectIdSessionsIndexRoute
  ProjectIdTracesIndexRoute: typeof ProjectIdTracesIndexRoute
  ProjectIdUsersIndexRoute: typeof ProjectIdUsersIndexRoute
  ProjectIdEvaluationsRunsRunIdRoute: typeof ProjectIdEvaluationsRunsRunIdRoute
  ProjectIdEvaluationsRunsIndexRoute: typeof ProjectIdEvaluationsRunsIndexRoute
}

const ProjectIdRouteRouteChildren: ProjectIdRouteRouteChildren = {
  ProjectIdConnectRoute: ProjectIdConnectRoute,
  ProjectIdSettingsRoute: ProjectIdSettingsRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdEvaluationsCompareRoute: ProjectIdEvaluationsCompareRoute,
  ProjectIdEvaluationsGatesRoute: ProjectIdEvaluationsGatesRoute,
  ProjectIdEvaluationsResultsRoute: ProjectIdEvaluationsResultsRoute,
  ProjectIdSessionsSessionIdRoute: ProjectIdSessionsSessionIdRoute,
  ProjectIdTracesTraceIdRoute: ProjectIdTracesTraceIdRoute,
  ProjectIdTracesCompareRoute: ProjectIdTracesCompareRoute,
  ProjectIdUsersUserIdRoute: ProjectIdUsersUserIdRoute,
  ProjectIdEvaluationsIndexRoute: ProjectIdEvaluationsIndexRoute,
  ProjectIdSessionsIndexRoute: ProjectIdSessionsIndexRoute,
  ProjectIdTracesIndexRoute: ProjectIdTracesIndexRoute,
  ProjectIdUsersIndexRoute: ProjectIdUsersIndexRoute,
  ProjectIdEvaluationsRunsRunIdRoute: ProjectIdEvaluationsRunsRunIdRoute,
  ProjectIdEvaluationsRunsIndexRoute: ProjectIdEvaluationsRunsIndexRoute,
}

const ProjectIdRouteRouteWithChildren = ProjectIdRouteRoute._addFileChildren(
  ProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRouteRoute: ProjectIdRouteRouteWithChildren,
  LlmModelsRoute: LlmModelsRoute,
  MembersRoute: MembersRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
